### ISSUE TITLE
build.sh file is missing

### ISSUE THREAD

**Issue by levyilan** [WiednerF/MoonGUI#1]
Hi,

build.sh file is missing from repository and package
Please add it.

MoonGUI]# make
cd moongui && make clean
make[1]: Entering directory `/root/MoonGUI/moongui'
npm cache clean
make[1]: Leaving directory `/root/MoonGUI/moongui'
git submodule update --init
cd ../ && ./build.sh
/bin/sh: ./build.sh: No such file or directory
make: *** [install] Error 127

**Comment by WiednerF** [comment]
The build.sh file is part of the required MoonGen project https://github.com/emmericp/MoonGen, for which this is a submodule. So it is not missing, you need just the other part of the project. 
Thanks.

I Just updated the documentation to make this clear. I have forgotten to write this. Thanks
